-- LEGACY: Må ikke bruges til ny 4.0.44-installation. Kør INSTALL-RAVRADAR-4.0.44.sql i stedet.
-- RavRadar 4.0.42
-- Sikker central lagring, dokumentbaserede rettigheder og verificerbar audit.

create or replace function public.ravradar_document_permission(p_document_key text)
returns text
language sql
immutable
as $$
  select case
    when p_document_key in ('rules','rule-history') then 'rules_edit'
    when p_document_key in ('water-level-station-routing','direction-reviews','zone-overrides','dmi-station-registry') then 'zones_weather_edit'
    when p_document_key in ('diagnostics-settings') then 'diagnostics_view'
    else 'full_admin'
  end;
$$;

create or replace function public.can_manage_ravradar_document(p_document_key text)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select public.is_ravradar_owner()
    or public.has_ravradar_permission('full_admin')
    or public.has_ravradar_permission(public.ravradar_document_permission(p_document_key));
$$;

create or replace function public.save_ravradar_admin_document(p_document_key text, p_payload jsonb)
returns table(document_key text, payload jsonb, version bigint, updated_at timestamptz, updated_by uuid)
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then
    raise exception 'LOGIN_REQUIRED' using errcode='42501';
  end if;
  if not public.can_manage_ravradar_document(p_document_key) then
    raise exception 'PERMISSION_DENIED_FOR_DOCUMENT: %', p_document_key using errcode='42501';
  end if;
  if p_document_key='rules'
     and coalesce((p_payload->>'schemaVersion'),'')=''
  then
    raise exception 'INVALID_RULE_DOCUMENT' using errcode='22023';
  end if;
  insert into public.admin_documents(document_key,payload,updated_by)
  values(p_document_key,p_payload,auth.uid())
  on conflict(document_key) do update set payload=excluded.payload,updated_by=auth.uid();
  return query
    select d.document_key,d.payload,d.version,d.updated_at,d.updated_by
    from public.admin_documents d where d.document_key=p_document_key;
end;
$$;

grant execute on function public.save_ravradar_admin_document(text,jsonb) to authenticated;

-- Direkte tabelskrivning lukkes. Skrivning skal gå gennem funktionen ovenfor.
drop policy if exists "authenticated admins manage documents" on public.admin_documents;
drop policy if exists ravradar_admin_documents_read on public.admin_documents;
create policy ravradar_admin_documents_read on public.admin_documents
for select to authenticated
using (public.can_manage_ravradar_document(document_key));

drop policy if exists "authenticated admins read document versions" on public.admin_document_versions;
drop policy if exists ravradar_admin_document_versions_read on public.admin_document_versions;
create policy ravradar_admin_document_versions_read on public.admin_document_versions
for select to authenticated
using (public.can_manage_ravradar_document(document_key));

revoke insert, update, delete on public.admin_documents from authenticated;
grant select on public.admin_documents to authenticated;
grant select on public.admin_document_versions to authenticated;

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  subject_key text,
  actor_id uuid references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_audit_log enable row level security;
drop policy if exists admin_audit_read on public.admin_audit_log;
create policy admin_audit_read on public.admin_audit_log for select to authenticated
using (public.is_ravradar_owner() or public.has_ravradar_permission('full_admin') or public.has_ravradar_permission('diagnostics_view'));

create or replace function public.audit_ravradar_document_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  insert into public.admin_audit_log(event_type,subject_key,actor_id,details)
  values('admin_document_saved',new.document_key,auth.uid(),jsonb_build_object('version',new.version));
  return new;
end;
$$;
drop trigger if exists ravradar_document_audit_trigger on public.admin_documents;
create trigger ravradar_document_audit_trigger after insert or update on public.admin_documents
for each row execute function public.audit_ravradar_document_change();

create or replace function public.save_ravradar_permissions(p_user_id uuid,p_permissions jsonb)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare k text;
begin
  if not (public.is_ravradar_owner() or public.has_ravradar_permission('full_admin') or public.has_ravradar_permission('experts_manage')) then
    raise exception 'PERMISSION_DENIED' using errcode='42501';
  end if;
  if exists(select 1 from public.profiles where id=p_user_id and role='owner') and not public.is_ravradar_owner() then
    raise exception 'OWNER_PROTECTED' using errcode='42501';
  end if;
  foreach k in array array['handbook_review','rules_edit','rules_publish','zones_weather_edit','diagnostics_view','experts_manage','full_admin'] loop
    insert into public.user_permissions(user_id,permission_key,enabled,updated_at)
    values(p_user_id,k,coalesce((p_permissions->>k)::boolean,false),now())
    on conflict(user_id,permission_key) do update set enabled=excluded.enabled,updated_at=now();
  end loop;
  insert into public.admin_audit_log(event_type,subject_key,actor_id,details)
  values('permissions_saved',p_user_id::text,auth.uid(),p_permissions);
end;
$$;
grant execute on function public.save_ravradar_permissions(uuid,jsonb) to authenticated;

-- Profil- og rettighedslæsning for ekspertadministratorer.
drop policy if exists profiles_owner_read on public.profiles;
create policy profiles_owner_read on public.profiles for select to authenticated
using (public.is_ravradar_owner() or id=auth.uid() or public.has_ravradar_permission('full_admin') or public.has_ravradar_permission('experts_manage'));
drop policy if exists permissions_owner_read on public.user_permissions;
create policy permissions_owner_read on public.user_permissions for select to authenticated
using (public.is_ravradar_owner() or user_id=auth.uid() or public.has_ravradar_permission('full_admin') or public.has_ravradar_permission('experts_manage'));
