-- RavRadar: Supabase gemmer kun levende brugerdata. Statiske kort og appfiler ligger i GitHub.
create table if not exists public.observations (
  id bigint generated by default as identity primary key,
  zone_id text not null,
  observed_at timestamptz not null default now(),
  hunt_mode text not null check (hunt_mode in ('waders', 'beach')),
  result text not null check (result in ('none', 'small', 'medium', 'good')),
  anonymous_id uuid not null,
  created_at timestamptz not null default now()
);
create index if not exists observations_zone_time_idx on public.observations (zone_id, observed_at desc);
alter table public.observations enable row level security;
create policy "anonymous observations can be inserted" on public.observations for insert to anon with check (observed_at > now() - interval '1 day');
create policy "observations are publicly readable" on public.observations for select to anon using (true);
