-- RavRadar 1.0: kun levende brugerobservationer gemmes i Supabase.
create table if not exists public.observations (
  id bigint generated by default as identity primary key,
  zone_id text not null check (char_length(zone_id) between 3 and 40),
  observed_at timestamptz not null default now(),
  hunt_mode text not null check (hunt_mode in ('waders', 'beach')),
  result text not null check (result in ('none', 'small', 'medium', 'good')),
  anonymous_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists observations_zone_time_idx on public.observations (zone_id, observed_at desc);
create index if not exists observations_created_idx on public.observations (created_at desc);
alter table public.observations enable row level security;

drop policy if exists "anonymous observations can be inserted" on public.observations;
create policy "anonymous observations can be inserted"
on public.observations for insert to anon
with check (
  observed_at between now() - interval '1 day' and now() + interval '10 minutes'
  and created_at between now() - interval '10 minutes' and now() + interval '10 minutes'
);

drop policy if exists "observations are publicly readable" on public.observations;
create policy "observations are publicly readable"
on public.observations for select to anon using (true);

-- Kan køres månedligt fra Supabase SQL Editor, hvis databasen en dag vokser:
-- delete from public.observations where created_at < now() - interval '5 years';
