import { submitHandbookReview, exportLocalHandbookDrafts, centralReviewStorageEnabled } from '../services/handbook-review-store.js';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const content=document.querySelector('#handbookContent'); const toc=document.querySelector('#handbookToc'); const dialog=document.querySelector('#reviewDialog'); const form=document.querySelector('#reviewForm');
let book=null;
async function boot(){const r=await fetch('./docs/handbook/content.json',{cache:'no-store'});book=await r.json();render(book.sections);}
function render(sections){toc.innerHTML=sections.map(s=>`<a href="#${esc(s.id)}">${esc(s.title)}</a>`).join('');content.innerHTML=`<section class="handbook-intro"><span class="eyebrow">Version ${esc(book.handbookVersion)}</span><h2>${esc(book.title)}</h2><p>Opdateret ${esc(book.updatedAt)}. Brug “Foreslå rettelse” ved det relevante afsnit.</p><p class="storage-state ${centralReviewStorageEnabled()?'ok':'warning'}">${centralReviewStorageEnabled()?'Central ekspertlagring er aktiv.':'Du er ikke logget ind til central lagring. Forslag gemmes som lokal nødkladde, indtil de kan afleveres centralt.'}</p></section>`+sections.map(s=>`<article id="${esc(s.id)}" data-search="${esc((s.title+' '+s.summary+' '+s.body.replace(/<[^>]+>/g,' ')).toLowerCase())}"><header><div><span class="eyebrow">Drejebog</span><h2>${esc(s.title)}</h2><p>${esc(s.summary)}</p></div><button class="review-button" data-review="${esc(s.id)}">Foreslå rettelse</button></header><div class="handbook-copy">${s.body}</div></article>`).join('');document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>openReview(b.dataset.review));}
function openReview(id){const s=book.sections.find(x=>x.id===id);form.reset();form.elements.sectionId.value=id;form.elements.sectionTitle.value=s.title;document.querySelector('#reviewStatus').textContent='';dialog.showModal();}
document.querySelector('#handbookSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#handbookContent article').forEach(a=>a.hidden=Boolean(q&&!a.dataset.search.includes(q)));});
document.querySelector('#exportDrafts').onclick=()=>exportLocalHandbookDrafts();
form.addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const button=document.querySelector('#submitReview');const status=document.querySelector('#reviewStatus');button.disabled=true;status.textContent='Gemmer…';const fd=new FormData(form);const result=await submitHandbookReview({handbookVersion:book.handbookVersion,sectionId:fd.get('sectionId'),sectionTitle:fd.get('sectionTitle'),expertise:fd.get('expertise'),issue:fd.get('issue'),proposal:fd.get('proposal'),reasoning:fd.get('reasoning'),expertName:fd.get('expertName'),organization:fd.get('organization')});status.textContent=result.central?'Rettelsen er gemt centralt med historik.':'Central lagring var ikke tilgængelig. Rettelsen er gemt som lokal nødkladde; eksportér den som sikkerhed.';button.disabled=false;if(result.central)setTimeout(()=>dialog.close(),1200);});
boot().catch(err=>content.innerHTML=`<p>Drejebogen kunne ikke indlæses: ${esc(err.message)}</p>`);