import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const review=await fs.readFile('js/services/handbook-review-store.js','utf8');
const site=await fs.readFile('js/services/site-function-test-service.js','utf8');
const weather=await fs.readFile('scripts/update-weather.mjs','utf8');
const hydrate=await fs.readFile('scripts/hydrate-deployed-weather.py','utf8');
const app=await fs.readFile('app.js','utf8');
assert.match(review,/created_by/);
assert.match(review,/responseError/);
assert.match(review,/status:'reviewing'/);
assert.doesNotMatch(review,/status:'testing'/);
assert.match(review,/deleteOrArchiveProbe/);
assert.match(site,/warnings\.length\?'warning':'passed'/);
assert.match(site,/verifyCriticalResources/);
assert.match(app,/ravradar:ready/);
assert.match(site,/Adminfaner åbner aktivt/);
assert.match(weather,/level\?\.cacheSource/);
assert.match(weather,/cachedStationLevels\(generatedAt\)/);
assert.match(hydrate,/merge_station_documents/);
assert.match(app,/ravradar:conditions-loaded/);
assert.match(app,/ravradar:zone-colors-ready/);
assert.match(app,/ravradar:forecast-ready/);
console.log('OK: 4.0.73 review, stationslivscyklus, helhedstest og performance-profiler er regressionssikret.');
