import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readProductionWorkflowSource } from './lib/production-workflow-sources.mjs';
const buildWorkflow=await readProductionWorkflowSource('build');
const bulk=fs.readFileSync('scripts/update-dmi-bulk.py','utf8');
const update=fs.readFileSync('scripts/update-weather.mjs','utf8');
const ravScoreContract=fs.readFileSync('js/core/ravscore-model-contract.js','utf8');
assert.match(buildWorkflow,/github\.run_id/);
assert.match(buildWorkflow,/actions\/cache\/restore@v6/);
assert.match(buildWorkflow,/actions\/cache\/save@v6/);
assert.match(buildWorkflow,/dmi-grib-v4/);
assert.match(buildWorkflow,/DMI_BULK_RAW_CACHE_MAX_MB: 4096/);
assert.match(bulk,/raw_cache_inventory/);
assert.match(bulk,/write_cache_audit/);
assert.match(bulk,/os\.utime\(path, None\)/);
assert.match(update,/DMI oceanObs stations', retries: DMI_MAX_RETRIES, dmi: false/);
assert.match(buildWorkflow,/Verify DMI station inventory for admin map/);
assert.match(ravScoreContract,/RAVSCORE_PUBLIC_FORECAST_HOURS = 118/);
assert.match(update,/ACCEPTED_FORECAST_HOURS = RAVSCORE_PUBLIC_FORECAST_HOURS/);
console.log('OK: bounded GitHub cache, station inventory gate and 118-hour acceptance.');
