import fs from 'node:fs/promises';
const app = await fs.readFile('app.js', 'utf8');
const ranking = app.indexOf("renderRanking();performance.mark?.('ravradar:ranking-ready')");
const paintYield = app.indexOf('await yieldToBrowser();', ranking);
const forecast = app.indexOf('const forecastCompleted=await renderNationalForecast()', ranking);
const arrows = app.indexOf('const installArrows=()=>');
const scheduled = app.indexOf('setTimeout(installArrows,0)', arrows);
if ([ranking,paintYield,forecast,arrows,scheduled].some(value=>value<0)) throw new Error('Opstartsmarkører, paint-yield eller deterministisk pilinstallation mangler.');
if (!(ranking < paintYield && paintYield < forecast && forecast < arrows && arrows < scheduled)) throw new Error('Dagens rangliste skal kunne males før den asynkrone prognose, og pile skal komme deterministisk sidst.');
if (app.includes('requestIdleCallback(installArrows')) throw new Error('Pileinstallationen må ikke igen afhænge af requestIdleCallback.');
if (!app.includes('async function renderNationalForecast()') || !app.includes('index%2===1') || !app.includes('Beregner 5-dages prognose… ${progress} %')) throw new Error('5-dages beregningen er ikke opdelt i browservenlige bidder.');
const mapView = await fs.readFile('js/map/map-view.js', 'utf8');
if (!mapView.includes('if (wasVisible) map.removeLayer(layer)') || !mapView.includes('layer.addTo(map);')) throw new Error('Pilelaget bygges ikke afkoblet fra kortet.');
console.log('OK: Dagens rangliste kan males før prognosen, prognosen giver browseren kontrollen tilbage, og pile installeres deterministisk bagefter.');
