import fs from 'node:fs/promises';
import { buildPublicConditions, buildPublicConditionDetails, compactJson, sha256Text } from './public-conditions-lib.mjs';

const full=JSON.parse(await fs.readFile('data/live/conditions.json','utf8'));
const publicText=await fs.readFile('data/live/public-conditions.json','utf8');
const detailsText=await fs.readFile('data/live/public-condition-details.json','utf8');
const manifest=JSON.parse(await fs.readFile('data/live/manifest.json','utf8'));
const expectedText=compactJson(buildPublicConditions(full));
const expectedDetailsText=compactJson(buildPublicConditionDetails(full));
if(detailsText!==expectedDetailsText) throw new Error('public-condition-details.json er ikke deterministisk.');
if(publicText!==expectedText) throw new Error('Den publicerede runtime er ikke byte-identisk med den fælles deterministiske projektion.');
if(manifest.datasetId!==full.datasetId) throw new Error('Manifest og fuld conditions har forskelligt datasetId.');
if(manifest.publicConditionsSha256!==sha256Text(publicText)) throw new Error('Manifestets SHA-256 for public-conditions er forkert.');
if(manifest.publicConditionDetailsSha256!==sha256Text(detailsText)) throw new Error('Manifestets SHA-256 for public-condition-details er forkert.');
if(manifest.publicConditionsBytes!==Buffer.byteLength(publicText)) throw new Error('Manifestets byteantal for public-conditions er forkert.');
if(manifest.publicConditionDetailsBytes!==Buffer.byteLength(detailsText)) throw new Error('Manifestets byteantal for public-condition-details er forkert.');
if(manifest.conditionsPath!=='./public-conditions.json') throw new Error('Manifestet peger ikke på public runtime.');
if(manifest.conditionDetailsPath!=='./public-condition-details.json') throw new Error('Manifestet peger ikke på public-condition-details.');
const workflow=await fs.readFile('.github/workflows/update-and-deploy.yml','utf8');
const occurrences=(workflow.match(/node scripts\/generate-public-conditions\.mjs/g)||[]).length;
if(occurrences!==1) throw new Error(`Workflowet skal genopbygge public runtime præcis én gang efter frisk vejr/proveniens; fandt ${occurrences}.`);
const runtimeIndex=workflow.indexOf('name: Rebuild deterministic public weather runtime before validation and deploy');
const weatherIndex=workflow.indexOf('name: Update central weather cache');
const provenanceIndex=workflow.indexOf('name: Attach scientific current provenance and exact DMI grid points');
const validateIndex=workflow.indexOf('name: Validate full project after fresh weather and current provenance');
if(!(weatherIndex<provenanceIndex && provenanceIndex<runtimeIndex && runtimeIndex<validateIndex)) throw new Error('Public runtime bygges ikke i den sikre rækkefølge efter frisk vejr og proveniens, men før validering.');
const updater=await fs.readFile('scripts/update-weather.mjs','utf8');
if(!updater.includes('writePublicRuntimeFromFull(output)')) throw new Error('Vejropdateringen bruger ikke den fælles runtime-writer.');
if(updater.includes('buildPublicConditions(output)')) throw new Error('Vejropdateringen har stadig en separat projektionsvej.');
console.log('OK: én deterministisk kilde styrer public runtime, manifest, workflow og vejrupdate.');
