import assert from "node:assert/strict";
import fs from "node:fs";
import { scoreRating, exceptionalScoreMark, SCORE_PRESENTATION } from "../js/core/score-engine.js";

assert.equal(scoreRating(100).level, "good");
assert.equal(scoreRating(90).exceptional, true);
assert.equal(scoreRating(89).exceptional, false);
assert.equal(scoreRating(75).level, "good");
assert.equal(scoreRating(74).level, "fair");
assert.equal(scoreRating(55).level, "fair");
assert.equal(scoreRating(54).level, "weak");
assert.equal(scoreRating(35).level, "weak");
assert.equal(scoreRating(34).level, "poor");
assert.equal(scoreRating(null).level, "unavailable");
assert.equal(exceptionalScoreMark(95), "★");
assert.equal(exceptionalScoreMark(70), "");
assert.equal(SCORE_PRESENTATION.exceptionalMinimum, 90);

const index = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("../style.css", import.meta.url), "utf8");
const infoPanel = fs.readFileSync(new URL("../js/ui/info-panel.js", import.meta.url), "utf8");
const browserAudit = fs.readFileSync(new URL("./audit-online-browser-4.0.237.py", import.meta.url), "utf8");
assert.doesNotMatch(index, /Fremragende|legend-dot excellent|score-symbol excellent/);
assert.match(index, /En stjerne viser usædvanligt gode forhold/);
assert.match(app, /exceptionalScoreMark\(item\.rankingDisplayScore\)/);
assert.match(app, /title="Områdescore"/);
assert.doesNotMatch(css, /\.rank-score\.excellent|\.score-badge\.excellent/);
assert.match(infoPanel, /Vandstandsændring på 3 timer/);
assert.match(browserAudit, /Vandstandsændring på 3 timer/);
console.log("Scoresignatur valideret: fire kortfarver og stjerne kun ved usædvanligt god ranglistescore.");
