import assert from 'node:assert/strict';
import fs from 'node:fs';
const admin=fs.readFileSync('js/ui/admin-dashboard.js','utf8');
const css=fs.readFileSync('admin.css','utf8');
assert.match(admin,/automaticStationRecommendation/);
assert.match(admin,/RavRadars automatiske valg/);
assert.match(admin,/Vis automatisk beregning/);
assert.match(admin,/Kopiér valget til administratorvalg/);
assert.match(admin,/Aktivt automatisk valg/);
assert.match(admin,/Aktivt administratorvalg/);
assert.match(admin,/inverse-distance/);
assert.match(css,/automatic-station/);
assert.doesNotMatch(css,/automatic-admin-station/);
assert.doesNotMatch(admin,/Begge valg/);
console.log('OK: admin viser automatisk primær/sekundær, kandidater og vægte, mens kortet kun viser den aktive routing.');
