import fs from 'node:fs/promises';
const app = await fs.readFile('app.js', 'utf8');
const i18n = await fs.readFile('js/i18n.js', 'utf8');
const ranking = app.indexOf("renderRanking();performance.mark?.('ravradar:ranking-ready')");
const paintYield = app.indexOf('await yieldToBrowser();', ranking);
const ready = app.indexOf("performance.mark?.('ravradar:ready')", paintYield);
const forecast = app.indexOf('const forecastCompleted=await renderNationalForecast()', ready);
const arrows = app.indexOf('const installArrows=()=>');
const scheduled = app.indexOf('setTimeout(installArrows,0)', arrows);
if ([ranking,paintYield,ready,forecast,arrows,scheduled].some(value=>value<0)) throw new Error('Opstartsmarkører, kompakt femdøgnsvisning eller deterministisk pilinstallation mangler.');
if (!(ranking < paintYield && paintYield < ready && ready < forecast && forecast < arrows && arrows < scheduled)) throw new Error('Kort/rangliste skal være klar før den kompakte femdøgnsvisning; pile skal planlægges sidst.');
if(!app.includes('function ensureConditionDetails()')||!app.includes('pending=loadConditionDetails({manifest:activeManifest,conditions:state.conditions})'))throw new Error('Den store detaljepakke har ikke en fælles behovsstyret indgang.');
const startupBlock=app.slice(app.indexOf('try {',app.indexOf('let logoTaps')),app.indexOf('// Vind- og strømpile'));
if(startupBlock.includes('loadConditionDetails('))throw new Error('Normal opstart må ikke hente den store detaljepakke.');
if (app.includes('requestIdleCallback(installArrows')) throw new Error('Pileinstallationen må ikke igen afhænge af requestIdleCallback.');
if (!app.includes('state.conditions?.nationalForecast?.modes?.[state.mode]') || !app.includes('async function renderNationalForecast()') || !app.includes('index%2===1')) throw new Error('Kompakt femdøgnsindeks eller browservenlig kompatibilitetsberegning mangler.');
if (!i18n.includes("'forecast.calculating'") || !i18n.includes('Beregner 5-dages prognose… {progress} %')) throw new Error('Den danske status for 5-dages beregningen mangler i i18n-kontrakten.');
const mapView = await fs.readFile('js/map/map-view.js', 'utf8');
if (!mapView.includes('if (wasVisible) map.removeLayer(layer)') || !mapView.includes('layer.addTo(map);')) throw new Error('Pilelaget bygges ikke afkoblet fra kortet.');
console.log('OK: Dagens rangliste og det kompakte femdøgnsindeks starter uden detaljepakken, mens pile installeres deterministisk bagefter.');
