-- RavRadar 4.0.37: varig ekspertfeedback til projektdrejebogen.
create table if not exists public.handbook_reviews (
  id uuid primary key,
  handbook_version text not null, section_id text not null, section_title text not null,
  expertise text not null, issue text not null, proposal text not null, reasoning text not null,
  expert_name text, organization text,
  status text not null default 'new' check (status in ('new','reviewing','accepted','implemented','rejected')),
  resolution_note text, client_payload jsonb not null default '{}'::jsonb,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  resolved_by uuid references auth.users(id) on delete set null, resolved_at timestamptz
);
create table if not exists public.handbook_review_versions (
  id bigint generated by default as identity primary key, review_id uuid not null references public.handbook_reviews(id) on delete restrict,
  snapshot jsonb not null, changed_by uuid references auth.users(id) on delete set null, changed_at timestamptz not null default now()
);
create or replace function public.version_handbook_review() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.handbook_review_versions(review_id,snapshot,changed_by) values(old.id,to_jsonb(old),auth.uid());
  new.updated_at=now();
  if new.status in ('implemented','rejected') and old.status is distinct from new.status then new.resolved_at=now(); new.resolved_by=auth.uid(); end if;
  return new;
end;$$;
drop trigger if exists handbook_reviews_version_trigger on public.handbook_reviews;
create trigger handbook_reviews_version_trigger before update on public.handbook_reviews for each row execute function public.version_handbook_review();
alter table public.handbook_reviews enable row level security;
alter table public.handbook_review_versions enable row level security;
drop policy if exists "authenticated users submit handbook reviews" on public.handbook_reviews;
create policy "authenticated users submit handbook reviews" on public.handbook_reviews for insert to authenticated with check(created_by=auth.uid());
drop policy if exists "users read own handbook reviews" on public.handbook_reviews;
create policy "users read own handbook reviews" on public.handbook_reviews for select to authenticated using(created_by=auth.uid());
drop policy if exists "authenticated admins manage handbook reviews" on public.handbook_reviews;
create policy "authenticated admins manage handbook reviews" on public.handbook_reviews for update to authenticated using(true) with check(true);
drop policy if exists "authenticated admins read handbook review versions" on public.handbook_review_versions;
create policy "authenticated admins read handbook review versions" on public.handbook_review_versions for select to authenticated using(true);
create index if not exists handbook_reviews_status_created_idx on public.handbook_reviews(status,created_at desc);
create index if not exists handbook_reviews_section_idx on public.handbook_reviews(section_id,created_at desc);

drop policy if exists "authenticated reviewers read handbook review queue" on public.handbook_reviews;
create policy "authenticated reviewers read handbook review queue" on public.handbook_reviews
for select to authenticated using(true);
